# Generated by Django 4.0.2 on 2022-02-11 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('product_category', models.CharField(choices=[('Caramels', (('Grey Sea Salt Caramels', 'Grey Sea Salt Caramels'), ('Huckleberry Caramels', 'Huckleberry Caramels'))), ('Truffles', (('Mocha', 'Mocha'), ('Raspberry', 'Raspberry')))], max_length=100)),
                ('chocolate_type', models.CharField(choices=[('Milk', 'Milk'), ('Dark', 'Dark'), ('White', 'White')], max_length=100)),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar_free', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('seasonal', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
