# Generated by Django 4.0.2 on 2022-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0002_product_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='chocolate_type',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Dark', 'Dark'), ('White', 'White'), ('Other', 'Other'), ('N/A', 'N/A')], max_length=100),
        ),
    ]
