# Generated by Django 4.0.2 on 2022-02-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0003_product_image_alter_product_chocolate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('lbs.', 'lbs.'), ('pc', 'piece')], default='', max_length=100),
        ),
    ]
