# Generated by Django 4.0.2 on 2022-02-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0005_company_openinghours_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_address',
            field=models.CharField(max_length=100),
        ),
    ]
