# Generated by Django 4.0.2 on 2022-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0007_remove_company_id_remove_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='location',
            name='hours',
        ),
        migrations.AddField(
            model_name='location',
            name='hours',
            field=models.ManyToManyField(to='order_form.OpeningHours'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
