# Generated by Django 4.0.2 on 2022-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0009_alter_company_options_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
