# Generated by Django 4.0.2 on 2022-02-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0011_rename_price_retail_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_wholesale',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
