# Generated by Django 4.0.2 on 2022-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0013_productgroup_remove_product_chocolate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
