# Generated by Django 4.0.2 on 2022-02-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0014_productgroup_active_productgroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_form.productgroup'),
        ),
    ]
