# Generated by Django 4.0.2 on 2022-02-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0016_remove_productgroup_chocolate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='white_chocolate',
            field=models.BooleanField(default=False),
        ),
    ]
