# Generated by Django 4.0.2 on 2022-02-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0017_alter_productgroup_not_applicable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
