# Generated by Django 4.0.2 on 2022-02-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0018_rename_product_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGroup',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_group',
            new_name='product',
        ),
    ]
