# Generated by Django 4.0.2 on 2022-02-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0020_alter_product_options_company_corporate_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='phone_number',
            new_name='location_phone',
        ),
    ]
