# Generated by Django 4.0.2 on 2022-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0021_rename_phone_number_location_location_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='open_now',
            field=models.BooleanField(default=False),
        ),
    ]
