# Generated by Django 4.0.2 on 2022-02-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0022_location_open_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='open_now',
        ),
    ]
