# Generated by Django 4.0.2 on 2022-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0023_remove_location_open_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chocolate_type',
            field=models.CharField(blank=True, choices=[('M', 'Milk'), ('D', 'Dark'), ('W', 'White'), ('O', 'Other'), ('N', 'N/A')], max_length=100),
        ),
    ]
